/**
 * Copyright (c) 2016-present Sonatype, Inc. All rights reserved.
 *
 * Includes the third-party code listed at https://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
apply plugin: 'com.android.library'

android {
  namespace 'com.inventage.sonatype.android.lib'
  compileSdk rootProject.ext.compileSdk

  defaultConfig {
    minSdk rootProject.ext.minSdk
    targetSdk rootProject.ext.targetSdk
    versionCode 1
    versionName '1.0'
  }
}

dependencies {
  implementation 'commons-collections:commons-collections:3.1'
}
